### ISSUE TITLE
Uniformative error message for conflicting physics diagnostic frequencies

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3config#156]
I recently came across the error:
```
Traceback (most recent call last):
  File "scripts/test_config.py", line 11, in <module>
    config_fv3config = config.to_fv3config()
  File "/usr/local/lib/python3.8/dist-packages/runtime/segmented_run/prepare_config.py", line 178, in to_fv3config
    file_configs_to_namelist_settings(
  File "/usr/local/lib/python3.8/dist-packages/runtime/diagnostics/fortran.py", line 158, in file_configs_to_namelist_settings
    raise NotImplementedError(
NotImplementedError: Cannot output physics diagnostics at multiple frequencies.
```
which is not very helpful. It should say what namelist options I need to fix.

**Comment by nbren12** [comment]
whoops. wrong repo.
